global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'latencymonitor'
    static_configs:
      - targets: ['latency-monitor:8081']
  - job_name: 'java-pipeline'
    static_configs:
      - targets: ['java-pipeline:8082']
